# permissions for end users to edit jobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: job-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: songf
    app.kubernetes.io/part-of: songf
    app.kubernetes.io/managed-by: kustomize
  name: job-editor-role
rules:
- apiGroups:
  - apps.songf.sh
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.songf.sh
  resources:
  - jobs/status
  verbs:
  - get
